default:
  image: node:12

build:
  stage: build
  script: npm install
  artifacts:
    paths:
      - node_modules

test:
  script: npm test

pages:
  stage: deploy
  script:
  - node_modules/.bin/preact build --no-prerender
  - mv build public
  artifacts:
    paths:
    - public
  only:
  - master
